---
layout: post
toc: true
categories: [CSP Big Idea 2]
title: Data Frames | Pandas | Intro 1
description: Data connections, trends, and correlation.  Pandas is introduced as it could be valuable for CPT and PBL.
courses: { csp: {week: 25} }
---

# Files To Get

1. Use wget or drag-and-drop the **_notebooks/CSP/big-ideas/big-idea-2** folder for this and other ipynb on pandas.

2. Use wget or drag-and-drop, in a subfolder named **data** in your **_notebookx** to grab data files.

- data.csv
- grade.json

3. Use wget or drag-and-drop, then copy image file and place into subfolder named **data_structures** in your **images** folder.  Grab the entire folder.

# Pandas and DataFrames
> In this lesson we will be exploring data analysis using Pandas.  

- College Board talks about ideas like 
    - Tools. "the ability to process data depends on users capabilities and their tools"
    - Combining Data.  "combine county data sets"
    - Status on Data"determining the artist with the greatest attendance during a particular month"
    - Data poses challenge. "the need to clean data", "incomplete data"


- [From Pandas Overview](https://pandas.pydata.org/docs/getting_started/index.html) -- When working with tabular data, such as data stored in spreadsheets or databases, pandas is the right tool for you. pandas will help you to explore, clean, and process your data. In pandas, a data table is called a DataFrame.

- DataFrame is a 2-dimensional labeled data structure with columns of potentially different types. It is similar to: 
    - a spreadsheet 
    - an SQL table
    - a JSON object with rows [] with nexted key-values {}

![DataFrame]({{site.baseurl}}/images/data_structures/pandas_dataframe.png)

In [ ]:
# uncomment the following line to install the pandas library
#!pip install pathlib
# !pip install python-dotenv
# !pip install pandas 
# !pip install requests

'''Pandas is used to gather data sets through its DataFrames implementation'''
# Top-level imports/config for this notebook
import os
from pathlib import Path

import pandas as pd
import requests
from dotenv import load_dotenv

# Stable path from home: ~/opencs/flask/.env
ENV_PATH = Path.home() / "opencs" / "flask" / ".env"
ENV_LOADED = load_dotenv(ENV_PATH)

print("cwd:", Path.cwd())
print("env path:", ENV_PATH)
print("env loaded:", ENV_LOADED)

Collecting pathlib
  Downloading pathlib-1.0.1-py3-none-any.whl.metadata (5.1 kB)
Downloading pathlib-1.0.1-py3-none-any.whl (14 kB)
Installing collected packages: pathlib
Successfully installed pathlib-1.0.1

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
cwd: /Users/johnmortensen/opencs/pages/_notebooks/CSP/big-ideas/big-idea-2
env path: /Users/johnmortensen/opencs/flask/.env
env loaded: True

# Cleaning Data

When looking at a data set, check to see what data needs to be cleaned. Examples include:
- Missing Data Points
- Invalid Data
- Inaccurate Data

Run the following code to see what needs to be cleaned

In [2]:
# Read the JSON file and convert it to a Pandas DataFrame 
# pd.read_json:  a method that reads a JSON and converts it to a DataFrame (df)
# df: a variable that holds the DataFrame
df = pd.read_json('data/grade.json')

# Print the DataFrame
print(df)

# Additional print statements to understand the DataFrame:
# print(df.info()) # prints a summary of the DataFrame, simmilar to database schema
# print(df.describe()) # prints statistics of the DataFrame
# print(df.head()) # prints the first 5 rows of the DataFrame
# print(df.tail()) # prints the last 5 rows of the DataFrame
# print(df.columns) # prints the columns of the DataFrame
# print(df.index) # prints the index of the DataFrame

# Questions:
# What part of the data set needs to be cleaned?
# From PBL learning, what is a good time to clean data?  
# Could you hav Garbage in, Garbage out problem if you don't clean the data?

   Student ID Year in School   GPA
0         123             12  3.57
1         246             10  4.00
2         578             12  2.78
3         469             11  3.45
4         324         Junior  4.75
5         313             20  3.33
6         145             12  2.95
7         167             10  3.90
8         235      9th Grade  3.15
9         nil              9  2.80
10        469             11  3.45
11        456             10  2.75

# Extracting Info

Take a look at some features that the Pandas library has that extracts info from the dataset

## DataFrame Extract Column

In [3]:
#print the values in the points column with column header
print(df[['GPA']])

print()

#try two columns and remove the index from print statement
print(df[['Student ID','GPA']].to_string(index=False))

     GPA
0   3.57
1   4.00
2   2.78
3   3.45
4   4.75
5   3.33
6   2.95
7   3.90
8   3.15
9   2.80
10  3.45
11  2.75

Student ID  GPA
       123 3.57
       246 4.00
       578 2.78
       469 3.45
       324 4.75
       313 3.33
       145 2.95
       167 3.90
       235 3.15
       nil 2.80
       469 3.45
       456 2.75

## DataFrame Sort

In [4]:
#sort values
print(df.sort_values(by=['GPA']))

print()

#sort the values in reverse order
print(df.sort_values(by=['GPA'], ascending=False))

   Student ID Year in School   GPA
11        456             10  2.75
2         578             12  2.78
9         nil              9  2.80
6         145             12  2.95
8         235      9th Grade  3.15
5         313             20  3.33
3         469             11  3.45
10        469             11  3.45
0         123             12  3.57
7         167             10  3.90
1         246             10  4.00
4         324         Junior  4.75

   Student ID Year in School   GPA
4         324         Junior  4.75
1         246             10  4.00
7         167             10  3.90
0         123             12  3.57
3         469             11  3.45
10        469             11  3.45
5         313             20  3.33
8         235      9th Grade  3.15
6         145             12  2.95
9         nil              9  2.80
2         578             12  2.78
11        456             10  2.75

## DataFrame Selection or Filter

In [5]:
#print only values with a specific criteria 
print(df[df.GPA > 3.00])

   Student ID Year in School   GPA
0         123             12  3.57
1         246             10  4.00
3         469             11  3.45
4         324         Junior  4.75
5         313             20  3.33
7         167             10  3.90
8         235      9th Grade  3.15
10        469             11  3.45

## DataFrame Selection Max and Min

In [6]:
print(df[df.GPA == df.GPA.max()])
print()
print(df[df.GPA == df.GPA.min()])

  Student ID Year in School   GPA
4        324         Junior  4.75

   Student ID Year in School   GPA
11        456             10  2.75

# Create your own DataFrame

Using Pandas allows you to create your own DataFrame in Python.

## Python Dictionary to Pandas DataFrame

In [7]:
import pandas as pd

#the data can be stored as a python dictionary
dict = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}
print("-------------Dictionary------------------")
print(dict)

#stores the data in a data frame
print("-------------Dict_to_DF------------------")
df = pd.DataFrame(dict)
print(df)

print("----------Dict_to_DF_labels--------------")
#or with the index argument, you can label rows.
df = pd.DataFrame(dict, index = ["day1", "day2", "day3"])
print(df)

-------------Dictionary------------------
{'calories': [420, 380, 390], 'duration': [50, 40, 45]}
-------------Dict_to_DF------------------
   calories  duration
0       420        50
1       380        40
2       390        45
----------Dict_to_DF_labels--------------
      calories  duration
day1       420        50
day2       380        40
day3       390        45

## Examine DataFrame Rows

In [8]:
print("-------Examine Selected Rows---------")
#use a list for multiple labels:
print(df.loc[["day1", "day3"]])

#refer to the row index:
print("--------Examine Single Row-----------")
print(df.loc["day1"])

-------Examine Selected Rows---------
      calories  duration
day1       420        50
day3       390        45
--------Examine Single Row-----------
calories    420
duration     50
Name: day1, dtype: int64

## Pandas DataFrame Information

In [9]:
#print info about the data set
print(df.info())

<class 'pandas.DataFrame'>
Index: 3 entries, day1 to day3
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   calories  3 non-null      int64
 1   duration  3 non-null      int64
dtypes: int64(2)
memory usage: 180.0+ bytes
None

# Example of larger data set

Pandas can read CSV and many other types of files, run the following code to see more features with a larger data set

In [10]:
import pandas as pd

#read csv and sort 'Duration' largest to smallest
df = pd.read_csv('data/data.csv').sort_values(by=['Duration'], ascending=False)

print("--Duration Top 10---------")
print(df.head(10))

print("--Duration Bottom 10------")
print(df.tail(10))

--Duration Top 10---------
     Duration  Pulse  Maxpulse  Calories
69        300    108       143    1500.2
79        270    100       131    1729.0
109       210    137       184    1860.4
60        210    108       160    1376.0
106       180     90       120     800.3
90        180    101       127     600.1
65        180     90       130     800.4
61        160    110       137    1034.4
62        160    109       135     853.0
67        150    107       130     816.0
--Duration Bottom 10------
     Duration  Pulse  Maxpulse  Calories
68         20    106       136     110.4
100        20     95       112      77.7
89         20     83       107      50.3
135        20    136       156     189.0
94         20    150       171     127.4
95         20    151       168     229.4
139        20    141       162     222.4
64         20    110       130     131.4
112        15    124       139     124.2
93         15     80       100      50.5

# APIs are a Source for Panda Data
> 3rd Party APIs are a great source for creating Pandas Data Frames.  
- Data can be fetched and resulting json can be placed into a Data Frame
- Observe output, this looks very similar to a Database

In [23]:
# ...existing code...
import pandas as pd
import requests

def fetch():
    uid = "hop"
    password = "123Hop!"

    auth_url = "https://flask.opencodingsociety.com/api/authenticate"
    user_url = "https://flask.opencodingsociety.com/api/id"

    with requests.Session() as session:
        auth_payload = {"uid": uid, "password": password}
        auth_resp = session.post(auth_url, json=auth_payload, timeout=15)

        print("auth status:", auth_resp.status_code)
        print("auth body:", auth_resp.text[:300])

        auth_resp.raise_for_status()

        resp = session.get(user_url, timeout=15)
        print("user status:", resp.status_code)
        print("user body:", resp.text[:300])

        resp.raise_for_status()
        data = resp.json()

    df = pd.DataFrame(data.get("personas", []))
    print(df)

fetch()  # required in notebook to produce output
# ...existing code...

auth status: 200
auth body: {"message":"Authentication for hop successful","user":{"class":["CSSE"],"name":"Grace Hopper","role":"User","uid":"hop"}}

user status: 200
user body: {"ap_exam":{},"class":["CSSE"],"email":"?","grade_data":{},"id":21,"is_admin":false,"is_teacher":false,"kasm_server_needed":false,"name":"Grace Hopper","password":"pbkdf2:sha256:1000000$HoJSnEsfU1$7875f0dfee037f190f4e1bd69199129dc7360dc5a2593a6d30c399aba54c15b7","personas":[{"persona_alias":"indy","
  persona_alias  persona_id          selected_at  uid  user_id  weight
0          indy           1  2026-03-01T01:14:35  hop       21       1
1         pixel           5  2026-03-01T01:14:40  hop       21       1
2         libra           9  2026-03-01T01:14:45  hop       21       1
3         flash          13  2026-03-01T01:14:49  hop       21       1

In [31]:
import os
from pathlib import Path
import pandas as pd
import requests
from dotenv import load_dotenv

def fetch():
    # notebook usually runs from repo root: /Users/johnmortensen/opencs/pages
    ENV_PATH = Path.home() / "opencs" / "flask" / ".env"
    loaded = load_dotenv(ENV_PATH)

    print("cwd:", Path.cwd())
    print("env loaded:", loaded, "from", ENV_PATH)

    uid = os.getenv("USER_UID")
    password = os.getenv("USER_PASSWORD")
    if not uid or not password:
        raise ValueError("Missing USER_UID or USER_PASSWORD in ../flask/.env")

    auth_url = "https://flask.opencodingsociety.com/api/authenticate"
    user_url = "https://flask.opencodingsociety.com/api/id"

    with requests.Session() as session:
        auth_payload = {"uid": uid, "password": password}
        auth_resp = session.post(auth_url, json=auth_payload, timeout=15)

        print("auth status:", auth_resp.status_code)
        print("auth body:", auth_resp.text[:300])
        auth_resp.raise_for_status()

        resp = session.get(user_url, timeout=15)
        print("user status:", resp.status_code)
        print("user body:", resp.text[:300])
        resp.raise_for_status()

        data = resp.json()

    df = pd.DataFrame(data.get("personas", []))
    print(df)

fetch()

cwd: /Users/johnmortensen/opencs/pages/_notebooks/CSP/big-ideas/big-idea-2
env loaded: True from /Users/johnmortensen/opencs/flask/.env
auth status: 200
auth body: {"message":"Authentication for hop successful","user":{"class":["CSSE"],"name":"Grace Hopper","role":"User","uid":"hop"}}

user status: 200
user body: {"ap_exam":{},"class":["CSSE"],"email":"?","grade_data":{},"id":21,"is_admin":false,"is_teacher":false,"kasm_server_needed":false,"name":"Grace Hopper","password":"pbkdf2:sha256:1000000$HoJSnEsfU1$7875f0dfee037f190f4e1bd69199129dc7360dc5a2593a6d30c399aba54c15b7","personas":[{"persona_alias":"indy","
  persona_alias  persona_id          selected_at  uid  user_id  weight
0          indy           1  2026-03-01T01:14:35  hop       21       1
1         pixel           5  2026-03-01T01:14:40  hop       21       1
2         libra           9  2026-03-01T01:14:45  hop       21       1
3         flash          13  2026-03-01T01:14:49  hop       21       1

In [ ]:
import os
import time
from pathlib import Path
import builtins as _b

import pandas as pd
import requests
from dotenv import load_dotenv
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

def fetch_all_users(page_size=25, max_pages=100, delay_sec=0.2):
    env_path = Path.home() / "opencs" / "flask" / ".env"
    loaded = load_dotenv(env_path, override=True)
    print("cwd:", Path.cwd())
    print("env loaded:", loaded, "from", env_path)

    uid = os.getenv("ADMIN_UID")
    password = os.getenv("ADMIN_PASSWORD")
    if not uid or not password:
        raise ValueError("Missing ADMIN_UID or ADMIN_PASSWORD in ~/opencs/flask/.env")

    auth_url = "https://flask.opencodingsociety.com/api/authenticate"
    candidate_user_urls = [
        "https://flask.opencodingsociety.com/api/user",
        "https://flask.opencodingsociety.com/api/users",
    ]

    def extract_rows(payload):
        if isinstance(payload, _b.list):
            return payload
        if isinstance(payload, _b.dict):
            return payload.get("users") or payload.get("personas") or payload.get("items") or []
        return []

    all_rows = []

    with requests.Session() as session:
        retry = Retry(
            total=3,
            connect=3,
            read=3,
            backoff_factor=0.6,
            status_forcelist=[429, 500, 502, 503, 504],
            allowed_methods=["GET", "POST"],
        )
        adapter = HTTPAdapter(max_retries=retry)
        session.mount("https://", adapter)
        session.mount("http://", adapter)

        auth_resp = session.post(auth_url, json={"uid": uid, "password": password}, timeout=(5, 20))
        print("auth status:", auth_resp.status_code)
        print("auth body:", auth_resp.text[:200])
        auth_resp.raise_for_status()

        if "application/json" in auth_resp.headers.get("content-type", ""):
            auth_json = auth_resp.json()
            token = auth_json.get("token") or auth_json.get("jwt") or auth_json.get("access_token")
            if token:
                session.headers.update({"Authorization": f"Bearer {token}"})

        selected_url = None
        for url in candidate_user_urls:
            try:
                test = session.get(url, params={"page": 1, "size": page_size}, timeout=(5, 45))
                if test.status_code != 404:
                    selected_url = url
                    print("selected endpoint:", selected_url, "status:", test.status_code)
                    break
            except requests.exceptions.ReadTimeout:
                print("discovery timeout on", url, "- trying next endpoint")

        if not selected_url:
            raise FileNotFoundError("No responsive users endpoint found (/api/user or /api/users).")

        for page in range(1, max_pages + 1):
            params = {"page": page, "size": page_size}
            read_timeout = 45

            for attempt in range(1, 4):
                try:
                    resp = session.get(selected_url, params=params, timeout=(5, read_timeout))
                    break
                except requests.exceptions.ReadTimeout:
                    print(f"page {page} timeout (attempt {attempt}), retrying...")
                    read_timeout *= 2
                    time.sleep(0.5 * attempt)
            else:
                print(f"page {page}: repeated timeout, stopping.")
                break

            print(f"page {page} status:", resp.status_code)
            if resp.status_code == 401:
                raise PermissionError("401 on users endpoint. Admin role/token required.")
            resp.raise_for_status()

            rows = extract_rows(resp.json())
            if not rows:
                print(f"page {page}: empty, stopping.")
                break

            all_rows.extend(rows)
            print(f"page {page}: +{len(rows)} rows (total {len(all_rows)})")

            if len(rows) < page_size:
                print(f"page {page}: partial page, stopping.")
                break

            time.sleep(delay_sec)
            
    df = pd.DataFrame(all_rows)
    df = df.loc[
        df["personas"].apply(lambda p: isinstance(p, list) and len(p) > 0),
        ["uid", "name", "personas"]
    ].head(50)
    print("final rows (personas only, max 50):", len(df))
    display(df)
    return df

all_users_df = fetch_all_users()

cwd: /Users/johnmortensen/opencs/pages/_notebooks/CSP/big-ideas/big-idea-2
env loaded: True from /Users/johnmortensen/opencs/flask/.env
auth status: 200
auth body: {"message":"Authentication for toby successful","user":{"class":[],"name":"Thomas Edison","role":"Admin","uid":"toby"}}

selected endpoint: https://flask.opencodingsociety.com/api/user status: 200
page 1 status: 200
page 1: +50 rows (total 50)
page 2 status: 200
page 2: +50 rows (total 100)
page 3 status: 200
page 3: +50 rows (total 150)
page 4 status: 200
page 4: +50 rows (total 200)
page 5 status: 200
page 5: +50 rows (total 250)
page 6 status: 200
page 6: +50 rows (total 300)
page 7 status: 200
page 7: +50 rows (total 350)
page 8 status: 200
page 8: +50 rows (total 400)
page 9 status: 200
page 9: +50 rows (total 450)
page 10 status: 200
page 10: +50 rows (total 500)
page 11 status: 200
page 11: +45 rows (total 545)
page 12 status: 200
page 12: empty, stopping.
final rows (personas only, max 50): 37

,uid,name,personas
0,toby,Thomas Edison,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
4,indy,Indy Technologist,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
5,salem,Salem Scrummer,"[{'persona_alias': 'salem', 'persona_id': 2, '..."
6,phoenix,Phoenix Planner,"[{'persona_alias': 'phoenix', 'persona_id': 3,..."
7,cody,Cody Closer,"[{'persona_alias': 'cody', 'persona_id': 4, 's..."
8,pixel,Pixel Gamer,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
9,cadence,Cadence Musician,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
10,ace,Ace Athlete,"[{'persona_alias': 'salem', 'persona_id': 2, '..."
11,marco,Marco Explorer,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
12,libra,Libra Scholar,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
13,nikola,Nikola Competitor,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
14,isaac,Isaac Builder,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
15,madam,Madam Ambassador,"[{'persona_alias': 'salem', 'persona_id': 2, '..."
16,flash,Flash Speedster,"[{'persona_alias': 'salem', 'persona_id': 2, '..."
17,parker,Parker Powerhouse,"[{'persona_alias': 'salem', 'persona_id': 2, '..."
18,merlin,Merlin Mastermind,"[{'persona_alias': 'salem', 'persona_id': 2, '..."
19,sky,Sky Visionary,"[{'persona_alias': 'salem', 'persona_id': 2, '..."
20,hop,Grace Hopper,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
87,aashrayr,Aashray Rajagopalan,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
248,SanPranav,Pranav Santhosh,"[{'persona_alias': 'ace', 'persona_id': 7, 'se..."
252,NickDiaz09,Nicolas Diaz,"[{'persona_alias': 'merlin', 'persona_id': 15,..."
273,aaguy-hue,Thomas Edison,"[{'persona_alias': 'salem', 'persona_id': 2, '..."
286,whitelunarium,Aneesh Deevi,"[{'persona_alias': 'flash', 'persona_id': 13, ..."
323,Ahaanv19,Ahaan,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
382,Rbojja23,Rohan Bojja,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
400,blackstar3092,Risha Guha,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
449,CyberLord09,Anvay Vahia,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
452,vibha1019,Vibha Mandayam,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
457,jm1021,John Mortensen,"[{'persona_alias': 'salem', 'persona_id': 2, '..."
462,adikatre,Aditya Katre,"[{'persona_alias': 'cody', 'persona_id': 4, 's..."
499,MoizL163,Moiz Lukmani,"[{'persona_alias': 'ace', 'persona_id': 7, 'se..."
500,anwitabandaru-gif,Anwita,"[{'persona_alias': 'merlin', 'persona_id': 15,..."
501,RudraBJoshi,Rudra Joshi,"[{'persona_alias': 'isaac', 'persona_id': 11, ..."
502,ruta-sir,Ruta,"[{'persona_alias': 'pixel', 'persona_id': 5, '..."
512,jchauhan08,Jaynee Chauhan,"[{'persona_alias': 'salem', 'persona_id': 2, '..."
514,mrboiisthebest,William Windle,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
525,NithikaVivek,Nithika Vivek,"[{'persona_alias': 'salem', 'persona_id': 2, '..."

In [ ]:
import os
import time
from pathlib import Path
import builtins as _b

import pandas as pd
import requests
from dotenv import load_dotenv
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

def fetch_all_users(per_page=50, max_pages=100, delay_sec=0.2):
    env_path = Path.home() / "opencs" / "flask" / ".env"
    loaded = load_dotenv(env_path, override=True)
    print("path:", env_path)
    print("env loaded:", loaded, "from", env_path)

    uid = os.getenv("ADMIN_UID")
    password = os.getenv("ADMIN_PASSWORD")
    if not uid or not password:
        raise ValueError("Missing ADMIN_UID or ADMIN_PASSWORD in ~/opencs/flask/.env")

    auth_url = "https://flask.opencodingsociety.com/api/authenticate"
    user_url = "https://flask.opencodingsociety.com/api/user"

    def extract_rows(payload):
        if isinstance(payload, _b.list):
            return payload
        if isinstance(payload, _b.dict):
            return payload.get("users") or payload.get("personas") or payload.get("items") or []
        return []

    all_rows = []

    with requests.Session() as session:
        retry = Retry(
            total=3,
            connect=3,
            read=3,
            backoff_factor=0.6,
            status_forcelist=[429, 500, 502, 503, 504],
            allowed_methods=["GET", "POST"],
        )
        adapter = HTTPAdapter(max_retries=retry)
        session.mount("https://", adapter)
        session.mount("http://", adapter)

        auth_resp = session.post(
            auth_url,
            json={"uid": uid, "password": password},
            timeout=(5, 20),
        )
        auth_resp.raise_for_status()

        # Optional bearer support
        if "application/json" in auth_resp.headers.get("content-type", ""):
            auth_json = auth_resp.json()
            token = auth_json.get("token") or auth_json.get("jwt") or auth_json.get("access_token")
            if token:
                session.headers.update({"Authorization": f"Bearer {token}"})

        for page in range(1, max_pages + 1):
            resp = session.get(
                user_url,
                params={"page": page, "per_page": per_page},
                timeout=(5, 30),
            )
            print(f"page {page} status:", resp.status_code)
            if resp.status_code == 401:
                raise PermissionError("401 on users endpoint. Admin role/token required.")
            resp.raise_for_status()

            data = resp.json()
            rows = extract_rows(data)

            if not rows:
                print(f"page {page}: empty, stopping.")
                break

            all_rows.extend(rows)
            print(f"page {page}: +{len(rows)} rows (total {len(all_rows)})")

            # stop when last page is smaller than per_page
            if len(rows) < per_page:
                print(f"page {page}: partial page, stopping.")
                break

            time.sleep(delay_sec)

    df = pd.DataFrame(all_rows)

    # keep only rows with persona data
    df = df.loc[
        df["personas"].apply(lambda p: isinstance(p, list) and len(p) > 0),
        ["uid", "name", "personas"]
    ].head(50)

    print("final rows (personas only, max 50):", len(df))
    display(df)
    return df

all_users_df = fetch_all_users(per_page=50)

page 1 status: 200
page 1: +50 rows (total 50)
page 2 status: 200
page 2: +50 rows (total 100)
page 3 status: 200
page 3: +50 rows (total 150)
page 4 status: 200
page 4: +50 rows (total 200)
page 5 status: 200
page 5: +50 rows (total 250)
page 6 status: 200
page 6: +50 rows (total 300)
page 7 status: 200
page 7: +50 rows (total 350)
page 8 status: 200
page 8: +50 rows (total 400)
page 9 status: 200
page 9: +50 rows (total 450)
page 10 status: 200
page 10: +50 rows (total 500)
page 11 status: 200
page 11: +45 rows (total 545)
page 11: partial page, stopping.
final rows (personas only, max 50): 37

,uid,name,personas
0,toby,Thomas Edison,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
4,indy,Indy Technologist,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
5,salem,Salem Scrummer,"[{'persona_alias': 'salem', 'persona_id': 2, '..."
6,phoenix,Phoenix Planner,"[{'persona_alias': 'phoenix', 'persona_id': 3,..."
7,cody,Cody Closer,"[{'persona_alias': 'cody', 'persona_id': 4, 's..."
8,pixel,Pixel Gamer,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
9,cadence,Cadence Musician,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
10,ace,Ace Athlete,"[{'persona_alias': 'salem', 'persona_id': 2, '..."
11,marco,Marco Explorer,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
12,libra,Libra Scholar,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
13,nikola,Nikola Competitor,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
14,isaac,Isaac Builder,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
15,madam,Madam Ambassador,"[{'persona_alias': 'salem', 'persona_id': 2, '..."
16,flash,Flash Speedster,"[{'persona_alias': 'salem', 'persona_id': 2, '..."
17,parker,Parker Powerhouse,"[{'persona_alias': 'salem', 'persona_id': 2, '..."
18,merlin,Merlin Mastermind,"[{'persona_alias': 'salem', 'persona_id': 2, '..."
19,sky,Sky Visionary,"[{'persona_alias': 'salem', 'persona_id': 2, '..."
20,hop,Grace Hopper,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
87,aashrayr,Aashray Rajagopalan,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
248,SanPranav,Pranav Santhosh,"[{'persona_alias': 'ace', 'persona_id': 7, 'se..."
252,NickDiaz09,Nicolas Diaz,"[{'persona_alias': 'merlin', 'persona_id': 15,..."
273,aaguy-hue,Thomas Edison,"[{'persona_alias': 'salem', 'persona_id': 2, '..."
286,whitelunarium,Aneesh Deevi,"[{'persona_alias': 'flash', 'persona_id': 13, ..."
323,Ahaanv19,Ahaan,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
382,Rbojja23,Rohan Bojja,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
400,blackstar3092,Risha Guha,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
449,CyberLord09,Anvay Vahia,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
452,vibha1019,Vibha Mandayam,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
457,jm1021,John Mortensen,"[{'persona_alias': 'salem', 'persona_id': 2, '..."
462,adikatre,Aditya Katre,"[{'persona_alias': 'cody', 'persona_id': 4, 's..."
499,MoizL163,Moiz Lukmani,"[{'persona_alias': 'ace', 'persona_id': 7, 'se..."
500,anwitabandaru-gif,Anwita,"[{'persona_alias': 'merlin', 'persona_id': 15,..."
501,RudraBJoshi,Rudra Joshi,"[{'persona_alias': 'isaac', 'persona_id': 11, ..."
502,ruta-sir,Ruta,"[{'persona_alias': 'pixel', 'persona_id': 5, '..."
512,jchauhan08,Jaynee Chauhan,"[{'persona_alias': 'salem', 'persona_id': 2, '..."
514,mrboiisthebest,William Windle,"[{'persona_alias': 'indy', 'persona_id': 1, 's..."
525,NithikaVivek,Nithika Vivek,"[{'persona_alias': 'salem', 'persona_id': 2, '..."

## Popcorn Hacks
> Portfolio Building  
- Add this Blog and other blogs to you own Blogging site.
- Have all lecture files saved to your files directory before Tech Talk starts. 
- Add this Blog to you own Blogging site.  In the Blog add notes and observations on each code cell.

> The next 6 weeks, the Teachers want you to improve your understanding of data structures and data science.  Your intention is to find some things to differentiate your individual College Board project, particularly if your project looks like all other projects.
- Look at this blog and others on data structures for todays date.  
- Create or Find your own dataset.  The suggestion is to use a JSON file, integrating with your CPT/PBL project would be ***Amazing***.
- Build frontend to backend to filter or use your data set in your CPT/PBL.
- When choosing a data set, think about the following...
    - Does it have a good sample size?
    - Is there bias in the data?
    - Does the data set need to be cleaned?
    - What is the purpose of the data set?
    - ...